language: node_js

node_js:
  - "node"

install:
  - npm install

script:
  - ng test --sourcemaps=false --browsers=ChromeHeadless --code-coverage=true --singleRun=true

notifications:
  email:
    on_success: never
    on_failure: never
